name: zuliadog
description: Aplicación de gestión veterinaria Zuliadog
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # --- Core Flutter ---
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  # --- Navegación / Estado ---
  go_router: ^16.2.1
  provider: ^6.1.2

  # --- Estado, almacenamiento y utilidades ---
  shared_preferences: ^2.2.3
  path: ^1.9.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  fluttertoast: ^8.2.4
  flutter_dotenv: ^6.0.0       # NO poner .env en assets (seguridad)
  intl: ^0.19.0

  # --- Archivos y documentos ---
  file_picker: ^10.3.3          # si prefieres, deja ^6.1.1
  excel: ^4.0.6
  image: ^4.1.7
  pdf: ^3.10.1
  printing: ^5.11.1
  syncfusion_flutter_xlsio: ^29.2.11
  syncfusion_flutter_pdfviewer: ^29.2.11

  # --- UI / Widgets ---
  flutter_typeahead: ^5.2.0
  dotted_border: ^3.1.0
  path_drawing: ^1.0.1
  fl_chart: ^1.1.0
  reorderable_grid_view: ^2.2.8

  # --- UI Avanzada / Layout ---
  window_manager: ^0.5.1
  syncfusion_flutter_calendar: ^29.2.11+1

  # --- (Opcionales específicos Web) ---
  universal_html: ^2.2.4
  flutter_dropzone: ^4.2.1

  # --- Backend / Servicios ---
  supabase_flutter: ^2.5.6

  flutter_animate: ^4.5.0

  # Charts modernos y suaves

  # Íconos delgados/premium (opcional)
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # ⚠️ NO incluir .env: se carga desde la raíz con flutter_dotenv
    
    - Assets/Docs/inventario.xlsx
    - Assets/Docs/pacientes.xlsx
    - Assets/Docs/recipes.pdf
    - Assets/Docs/historias.pdf

    - Assets/Images/App.png
    - Assets/Images/logo_icon.png
    - Assets/Images/CodigoQR.png
    - Assets/Images/phone_icon.png
    - Assets/Images/Iconohuella.png
    - Assets/Images/upload.png
    - Assets/Emojis/
    - Assets/Images/logo.png

  fonts:
    - family: Satoshi
      fonts:
        - asset: Assets/Fonts/Satoshi-Regular.otf
        - asset: Assets/Fonts/Satoshi-Bold.otf
          weight: 700
        - asset: Assets/Fonts/Satoshi-Light.otf
          weight: 300
        - asset: Assets/Fonts/Satoshi-Medium.otf
          weight: 500
        - asset: Assets/Fonts/Satoshi-Black.otf
          weight: 900
        - asset: Assets/Fonts/Satoshi-Italic.otf
          style: italic
        - asset: Assets/Fonts/Satoshi-BoldItalic.otf
